# Generated by Django 5.1.6 on 2025-02-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
