# Generated by Django 5.1.6 on 2025-02-26 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
