# Generated by Django 5.1.6 on 2025-02-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_room_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Room area in square meters', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='max_guest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='booking.amenity'),
        ),
    ]
